/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package mx.gob.cnbv.web.api;

import mx.gob.cnbv.web.api.model.Reporte;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2018-09-13T03:06:13.088-05:00[America/Mexico_City]")

@Api(value = "reportes", description = "the reportes API")
public interface ReportesApi {

    default ReportesApiDelegate getDelegate() {
        return new ReportesApiDelegate() {};
    }

    @ApiOperation(value = "consultarReporteInfo", nickname = "getReporteUsingGET", notes = "", response = Reporte.class, authorizations = {
        @Authorization(value = "bearerAuth")
    }, tags={ "reporte-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Reporte.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/reportes/{id}",
        produces = { "*/*" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Reporte> getReporteUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id) {
        return getDelegate().getReporteUsingGET(id);
    }

}
